import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newContext({ viewport: { width: 1500, height: 950 } }).then(c=>c.newPage())
const errs=[]; p.on('console',m=>{if(m.type()==='error')errs.push(m.text())}); p.on('pageerror',e=>errs.push(String(e)))
p.on('dialog', d=>d.accept())
await p.goto('http://localhost:5219/', { waitUntil:'networkidle' })
await p.waitForSelector('.app-shell')
await p.click('button[aria-label="Menu fichier"]')
await p.click('button[role="menuitem"]:has-text("Charger le cadrage locasyst")')
await p.waitForTimeout(900)
const R={}
R.edgesBefore = await p.locator('.vue-flow__edge').count()
// zoom in a bit so handles are clickable (fit is too small). Use fit then wheel? just proceed at fit.
const src = p.locator('.vue-flow__node-feature:has-text("SOC-13")').first()
const tgt = p.locator('.vue-flow__node-feature:has-text("SOC-01")').first()
await src.hover()
await p.waitForTimeout(200)
// right-side source handle (free)
const h = src.locator('.vue-flow__handle-right.source').last()
R.handleCount = await src.locator('.vue-flow__handle').count()
const hb = await h.boundingBox()
const tb = await tgt.boundingBox()
if(!hb||!tb){ R.err='no box'; console.log(JSON.stringify(R)); await b.close(); process.exit(0) }
await p.mouse.move(hb.x+hb.width/2, hb.y+hb.height/2)
await p.mouse.down()
await p.mouse.move(tb.x+tb.width/2, tb.y+tb.height/2, {steps:12})
await p.waitForTimeout(150)
await p.mouse.up()
await p.waitForTimeout(500)
R.edgesAfter = await p.locator('.vue-flow__edge').count()
R.quickMenu = await p.locator('.quick-create').count()
R.errs = errs
console.log(JSON.stringify(R,null,2))
await b.close()
