import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newContext({ viewport: { width: 1500, height: 950 } }).then(c=>c.newPage())
const errs=[]; p.on('console',m=>{if(m.type()==='error')errs.push(m.text())}); p.on('pageerror',e=>errs.push(String(e)))
p.on('dialog', d=>d.accept())
const R={}
await p.goto('http://localhost:5219/', { waitUntil:'networkidle' })
await p.waitForSelector('.app-shell')
const mainZoom = ()=>p.evaluate(()=>{ const ps=[...document.querySelectorAll('.vue-flow__transformationpane')].filter(e=>!e.closest('.vue-flow__minimap')); const e=ps[0]; return e?getComputedStyle(e).transform:'none' })
await p.click('button[role="tab"]:has-text("Fonctionnalités")'); await p.waitForTimeout(700)
R.zoomEmpty = await mainZoom()
const pane=await p.$('.vue-flow__pane'); const pb=await pane.boundingBox()
await p.click('button[aria-label^="Fonctionnalité"]', {modifiers:['Shift']})
await p.mouse.click(pb.x+350, pb.y+300); await p.waitForTimeout(250)
await p.mouse.click(pb.x+350, pb.y+560); await p.waitForTimeout(250)
await p.keyboard.press('v'); await p.keyboard.press('Escape'); await p.waitForTimeout(300)
R.zoomAfter = await mainZoom()
R.feats=await p.locator('.vue-flow__node-feature').count()
const A=p.locator('.vue-flow__node-feature').nth(0)
R.Aw = await A.evaluate(el=>Math.round(el.getBoundingClientRect().width))
R.e0=await p.locator('.vue-flow__edge').count()
const bA=await A.boundingBox(); const B=p.locator('.vue-flow__node-feature').nth(1); const bB=await B.boundingBox()
await A.hover(); await p.waitForTimeout(200)
await p.mouse.move(bA.x+bA.width/2, bA.y+bA.height-3); await p.mouse.down()
await p.mouse.move(bB.x+bB.width/2, bB.y+bB.height/2, {steps:20}); await p.waitForTimeout(200); await p.mouse.up()
await p.waitForTimeout(500)
R.e1=await p.locator('.vue-flow__edge').count()
R.errs=errs
await p.screenshot({ path: new URL('./mv2.png', import.meta.url).pathname, clip:{x:pb.x+180,y:pb.y+160,width:520,height:600} })
console.log('MV2 '+JSON.stringify(R))
await b.close()
