import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newContext({ viewport: { width: 1600, height: 950 } }).then(c=>c.newPage())
const logs=[]; p.on('console',m=>{const t=m.text(); if(t.includes('[FLOOOW-SNAP]')) logs.push(t)})
p.on('dialog',d=>d.accept())
const R={}
await p.goto('http://localhost:5219/', { waitUntil:'networkidle' }); await p.waitForSelector('.app-shell')
await p.click('button[role="tab"]:has-text("Fonctionnalités")'); await p.waitForTimeout(500)
const pane=await p.$('.vue-flow__pane'); const pb=await pane.boundingBox()
await p.click('button[aria-label^="Module"]', {modifiers:['Shift']})
await p.mouse.click(pb.x+400, pb.y+250); await p.waitForTimeout(300)
await p.mouse.click(pb.x+430, pb.y+560); await p.waitForTimeout(300)
await p.keyboard.press('v'); await p.waitForTimeout(200)
const A=p.locator('.vue-flow__node-module').nth(0), B=p.locator('.vue-flow__node-module').nth(1)
const B0=await B.boundingBox()
// small wiggle drag of B (should trigger snapFunctional)
await p.mouse.move(B0.x+40, B0.y+15); await p.mouse.down()
await p.mouse.move(B0.x+30, B0.y+18, {steps:6}); await p.waitForTimeout(100)
await p.mouse.move(B0.x+20, B0.y+15, {steps:6}); await p.waitForTimeout(100)
await p.mouse.up(); await p.waitForTimeout(300)
R.snapLogs = logs.slice(0,6)
console.log('SNAP3 '+JSON.stringify(R,null,1))
await b.close()
