import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newContext({ viewport: { width: 1600, height: 950 } }).then(c=>c.newPage())
p.on('dialog', d=>d.accept())
const R={}
await p.goto('http://localhost:5219/', { waitUntil:'networkidle' })
await p.waitForSelector('.app-shell')
const vpT = ()=>p.$eval('.vue-flow__viewport', el=>el.style.transform)
R.z_load = await vpT()
await p.click('button[role="tab"]:has-text("Fonctionnalités")'); await p.waitForTimeout(600)
R.z_func = await vpT()
const pane=await p.$('.vue-flow__pane'); const pb=await pane.boundingBox()
await p.click('button[aria-label^="Fonctionnalité"]', {modifiers:['Shift']})
await p.mouse.click(pb.x+300, pb.y+250); await p.waitForTimeout(300)
R.z_after1 = await vpT()
R.feat1 = await p.locator('.vue-flow__node-feature').count()
console.log('ZOOM '+JSON.stringify(R))
await b.close()
